# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# image: gitpod/workspace-full:2023-03-06-18-43-51
image:
  file: Dockerfile
tasks:
  - init: |
      npm install
      sleep 120
  - command: |
      echo "Hellow!"
github:
  prebuilds:
    master: true
vscode:
  extensions:
    - vscodevim.vim
