# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:kylos101-jam-dev-image.2
  # file: Dockerfile
tasks:
  - init: |
      npm install
      sleep 120
  - command: |
      echo "Hellow!"
github:
  prebuilds:
    master: true
vscode:
  extensions:
    - vscodevim.vim
