# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      npm install
      sleep 120
  - command: |
      echo "Hellow!"
github:
  prebuilds:
    master: true
vscode:
  extensions:
    - vscodevim.vim